config/routes.rb
Basestar::Application.routes.draw do
  resources :ais do
    get 'download', :on => :member
    get 'public', :on => :collection
  end

  devise_for :users

  get "hi" => "hi#index"
  get "hi/secret"

  root :to => "hi#index"
end

app/models/ai.rb
class Ai < ActiveRecord::Base
  attr_accessible :name, :source, :user_id, :public

  belongs_to :user

  validates_presence_of :name, :source, :user, :file_name
  validates_uniqueness_of :name
  validates_format_of :file_name, :with => /\.rb$/, :message => "must be a ruby file"

  before_validation :set_name_from_file_name

  scope :public, where(:public => true)

  def set_name_from_file_name
    self.name = File.basename(self.file_name, ".*").camelize if self.file_name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :ais
end

app/controllers/ais_controller.rb
class AisController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :public, :download]
  before_filter :get_ai, :only => [:edit, :update, :destroy]
  before_filter :get_public_ai, :only => [:show, :download]

  def index
    if user_signed_in?
      @ais = current_user.ais
    else
      redirect_to :action => "public"
    end
  end

  def public
    @ais = Ai.public
    render "index"
  end

  def show
  end

  def download
    send_data @ai.source, :filename => @ai.file_name
  end

  def new
    @ai = Ai.new
  end

  def create
    @ai = current_user.ais.build(params[:ai])

    if params[:ai][:source]
      @ai.source = File.read(params[:ai][:source].tempfile) 
      @ai.file_name = params[:ai][:source].original_filename
    end

    if @ai.save
      redirect_to @ai, :notice => "Successfully created ai."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    @ai.attributes = params[:ai]

    if params[:ai][:source]
      @ai.source = File.read(params[:ai][:source].tempfile) 
      @ai.file_name = params[:ai][:source].original_filename
    end

    if @ai.save
      redirect_to @ai, :notice  => "Successfully updated ai."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @ai.destroy
    redirect_to ais_url, :notice => "Successfully destroyed ai."
  end

  private

  # If the user is signed in, redirects to ais_path. Else, redirects
  # to public_ais_path.
  def redirect_to_base(options = {})
    path = user_signed_in? ? ais_path : public_ais_path
    redirect_to path, options
  end

  def get_ai(options = {})
    @ai = Ai.find(params[:id])
    unless @ai.user == current_user || (options[:public] && @ai.public?)
      redirect_to_base :alert => "You did it wrong"
    end
  end

  def get_public_ai
    get_ai :public => true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hi_controller.rb
class HiController < ApplicationController
  before_filter :authenticate_user!, :only => :secret

  def index
  end

  def secret
  end
end

app/helpers/ais_helper.rb
module AisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/hi_helper.rb
module HiHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/ais/_form.html.erb
<%= form_for @ai, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :source %><br />
    <%= f.file_field :source %>
  </p>
  <p>
    <%= f.label :public %><br />
    <%= f.check_box :public %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/ais/edit.html.erb
<% title "Edit Ai" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @ai %> |
  <%= link_to "View All", ais_path %>
</p>

app/views/ais/index.html.erb
<% title "Ais" %>

<table>
  <% for ai in @ais %>
    <tr>
      <td><%= ai.name %></td>
      <td><%= link_to "Show", ai %></td>
      <% if ai.user == current_user %>
        <td><%= link_to "Edit", edit_ai_path(ai) %></td>
        <td><%= link_to "Destroy", ai, :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Ai", new_ai_path %></p>

app/views/ais/new.html.erb
<% title "New Ai" %>

<%= render 'form' %>

<p><%= link_to "Back to List", ais_path %></p>

app/views/ais/show.html.erb
<% title "Ai" %>

<p>
  <strong>Name:</strong>
  <%= @ai.name %>
</p>
<p>
  <strong>File Name:</strong>
  <%= @ai.file_name %>
</p>
<p>
  <% if @ai.public? %>
    Public <%= link_to "Download", download_ai_path(@ai) %>
  <% else %>
    Private
  <% end %>
</p>

<pre class="prettyprint lang-rb"><%= @ai.source %></pre>

<p>
  <% if @ai.user == current_user %>
    <%= link_to "Edit", edit_ai_path(@ai) %> |
    <%= link_to "Destroy", @ai, :confirm => 'Are you sure?', :method => :delete %> |
  <% end %>
  <%= link_to "View All", ais_path %>
</p>

app/views/hi/index.html.erb
<h1>Hi</h1>
<p><%= link_to "secret", :controller => "hi", :action => "secret" %></p>

app/views/hi/secret.html.erb
<h1>Secret!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>.
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or
          <%= link_to "Sign in", new_user_session_path %>
        <% end %>    
      </div>
      <br />
      <div id="site_nav">
        <% if user_signed_in? %>
          <%= link_to "My AIs", ais_path %> |
        <% end %>
        <%= link_to "Public AIs", public_ais_path %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>